//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waSemana12
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_almacenEntities : DbContext
    {
        public BD_almacenEntities()
            : base("name=BD_almacenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
    
        public virtual int usp_actualizar_producto(string nom, Nullable<decimal> pre, Nullable<int> stk, Nullable<System.DateTime> fvc, Nullable<int> idcat, Nullable<int> id)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var preParameter = pre.HasValue ?
                new ObjectParameter("pre", pre) :
                new ObjectParameter("pre", typeof(decimal));
    
            var stkParameter = stk.HasValue ?
                new ObjectParameter("stk", stk) :
                new ObjectParameter("stk", typeof(int));
    
            var fvcParameter = fvc.HasValue ?
                new ObjectParameter("fvc", fvc) :
                new ObjectParameter("fvc", typeof(System.DateTime));
    
            var idcatParameter = idcat.HasValue ?
                new ObjectParameter("idcat", idcat) :
                new ObjectParameter("idcat", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_producto", nomParameter, preParameter, stkParameter, fvcParameter, idcatParameter, idParameter);
        }
    
        public virtual int usp_borrar_producto(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_producto", idParameter);
        }
    
        public virtual int usp_insertar_producto(string nom, Nullable<decimal> pre, Nullable<int> stk, Nullable<System.DateTime> fvc, Nullable<int> idcat)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var preParameter = pre.HasValue ?
                new ObjectParameter("pre", pre) :
                new ObjectParameter("pre", typeof(decimal));
    
            var stkParameter = stk.HasValue ?
                new ObjectParameter("stk", stk) :
                new ObjectParameter("stk", typeof(int));
    
            var fvcParameter = fvc.HasValue ?
                new ObjectParameter("fvc", fvc) :
                new ObjectParameter("fvc", typeof(System.DateTime));
    
            var idcatParameter = idcat.HasValue ?
                new ObjectParameter("idcat", idcat) :
                new ObjectParameter("idcat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insertar_producto", nomParameter, preParameter, stkParameter, fvcParameter, idcatParameter);
        }
    
        public virtual ObjectResult<usp_listar_categoria_Result> usp_listar_categoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_categoria_Result>("usp_listar_categoria");
        }
    
        public virtual ObjectResult<usp_listar_producto_Result> usp_listar_producto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_producto_Result>("usp_listar_producto");
        }
    }
}
