//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waSemana12
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int idpro { get; set; }
        public string nompro { get; set; }
        public decimal prepro { get; set; }
        public int stkpro { get; set; }
        public System.DateTime fvcpro { get; set; }
        public int idcat { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
